version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to DockerHub...
      - docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
      - REPOSITORY_URI="158699263176.dkr.ecr.us-east-1.amazonaws.com/springboot-ecr"
      - CONTAINER_NAME="springboot-ecr"
      - IMAGE_TAG="latest"
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $REPOSITORY_URI:$IMAGE_TAG .
  post_build:
    commands:
      - echo Build completed on `date`
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"'$CONTAINER_NAME'","imageUri":"%s"}]' $REPOSITORY_URI:$IMAGE_TAG > builddefinition.json
artifacts:
    files: builddefinition.json
